name: PR Check

on:
  pull_request:
    - next
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: install deps
        run: npm install

      - name: check
        run: npx svelte-check --tsconfig ./tsconfig.json

      - name: test
        run: npx jest
      
      - name: build
        run: npm run build
