name: PR Check

on:
  pull_request:
    branches:
      - next
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: install deps
        run: npm install

      - name: check
        run: npx svelte-check --tsconfig ./tsconfig.json --ignore ./cypress

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: install deps
        run: npm install

      - name: check
        run: npm run format:check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Add ${{ github.base_ref }} branch
        run: git branch -f --create-reflog ${{ github.base_ref }} origin/${{ github.base_ref }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: install deps
        run: npm install

      - name: test
        run: npm run test -- --changedSince=${{ github.base_ref }} --coverage --coverageReporters=cobertura

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Generate Diff Coverage
        run: |
          # stop-gap until Jest adds a way of doing this for us
          python -m pip install diff-cover
          # Get diff coverage
          DIFF_COVERAGE="$(diff-cover coverage/cobertura-coverage.xml --compare-branch=${{ github.base_ref }})"

          echo 'DIFF_COVERAGE<<EOF' >> "$GITHUB_ENV"
          echo "$DIFF_COVERAGE" >> "$GITHUB_ENV"
          echo 'EOF' >> "$GITHUB_ENV"

      - name: Report Coverage
        uses: actions/github-script@v5
        with:
          script: |
            const diffCoverage = process.env.DIFF_COVERAGE;
            const [_, coverageInfo, summary] = diffCoverage.split('-------------').map(s => s.trim()).filter(s => s.length !== 0);
            // Include a smaller message if there is no coverage information for the diff
            const reportBody = !summary ? ````n${coverageInfo}n```` : ````
            ${summary}
            ```

            <details>
            <summary>Detailed Coverage Report</summary>

            ```
            ${coverageInfo}
            ```
            </details>`;
            const templatedMessage = `##  Coverage Report:nn${reportBody}`;
            const {data: existingComments} = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });

            const githubActionComments = existingComments.filter((comment) => comment.user.login === 'github-actions[bot]' && comment.body.includes('Coverage Report'));
            if (githubActionComments.length) {
              const latestComment = githubActionComments.reverse()[0]

              if (latestComment.body === templatedMessage) {
                core.info('Diff comment with the same message already exists - not posting.')
                return
              }
            }

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: templatedMessage
            });
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: install deps
        run: npm install

      - name: build
        run: npm run build
